### PR TITLE
Added an option for a delay before triggering alerts

### PR DESCRIPTION
**Pull request by motley74**
Adds a preference setting to specify a delay (no delay by default)
Adds a check if contacts are closed before the alert is sent and logs message instead
Move forecast to a state variable so it can be used by multiple functions (needed since you cannot pass data to functions used in runIn() as far as I know)

Other minor code changes to suit my preference for else formatting, this can be removed if not wanted, just let me know.

### CODE REVIEW

**Comment by imbrianj** [comment]
Can you add you email to the attribution comment at the top?

**Comment by motley74** [comment]
I can, do you prefer to use my code or yours?  I was just testing your version and so far it seems to work so I am fine with either.

**Comment by imbrianj** [comment]
I'm cool with yours, as-is.  Looks cleaner, IMO.

**Comment by motley74** [comment]
Let me now if there is anything else you want included.

**Comment by imbrianj** [comment]
Looks good - thanks!  :+1:

**Comment by motley74** [comment]
Thank you, please let me know once ST accepts it or add me to the request if you can so I can track this, for now I will run it as a custom app as you mentioned.

**Comment by imbrianj** [comment]
The repo the update PR was sent to is private :disappointed:

**Comment by motley74** [comment]
Yeah, I am not sure what process you followed but I think now you have to submit a request via the ST IDE.  I was able to submit a PR to the repo for a device handler update and pinged Tim Slagle on the community forums and he forwarded that on to the device guy but I think for custom apps you have to follow the process in the IDE.

**Comment by imbrianj** [comment]
I have access to the private repo (read only) that I think is the correct one.  I just filed a PR directly since I didn't see the IDE PR in there.  In either case - I've tried updating both places.

**Comment by motley74** [comment]
Is the below repo the one you did a PR against?  I don't see the PR so might not be correct, it is also not a private repo.  I have 2 PRs there that were submitted a few days ago, once was a direct PR that Tim slagle pinged the hardware guy on and the other was a submission via the IDE under "Publication Requests"

https://github.com/SmartThingsCommunity/SmartThingsPublic/pulls

**Comment by imbrianj** [comment]
No, I did my PR against another repo.  I did also use the IDE tool - but do not see my PR in the repo you cited.  The IDE no longer allows me to make a PR with that app.

**Comment by motley74** [comment]
I think you may need to fork the public repo and then set that up in the IDE for your app for it to work with the submission process.  I would suggest just submitting the PR against the public repo and then we can ping someone on the forums to help get it reviewed like I did with one of mine.  If you want me to reach out to someone just let me know, I am willing to do anything I can to help get this added.

**Comment by imbrianj** [comment]
https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/789

**Pull request merged**
